openapi: 3.0.1
info:
  version: 1.0.0
  title: Hacker News
  description: ""
servers:
  - url: 'https://afternoon-hamlet-99408.herokuapp.com'
paths:
  /api/posts/url:
    get:
      tags:
      - contributions
      summary: Retrieves all the url Contributions
      operationId: getAllUrlContributions
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contribution'
  
  /api/posts/ask:
    get:
      tags:
      - contributions
      summary: Retrieves all the ask Contributions
      operationId: getAllAskContributions
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Contribution'
                  
  /api/posts/{id}:
    get:
      tags:
      - contribution
      summary: Finds a Post
      operationId: getContribution
      parameters:
      - name: id
        in: path
        description: Contribution id
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Contribution
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        404:
          description: 'Error: Not Found'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
              examples:
                errorExample:
                  $ref: '#/components/examples/error404'

components:
  schemas:
    Contribution:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        contr_type:
          type: string
          minLength: 4
          example: 'My type'
        contr_subtype:
          type: string
          minLength: 4
          example: 'My subtype'
        content:
          type: string
          minLength: 4
          maxLength: 280
          example: 'My content'
        user_id:
          type: integer
          format: int32
        url:
          type: string
          minLength: 4
          maxLength: 280
          example: 'My url'
        upvote:
          type: integer
          format: int32
        parent_id:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    
    Comment:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        contr_type:
          type: string
          minLength: 4
          example: 'My type'
        contr_subtype:
          type: string
          minLength: 4
          example: 'My subtype'
        content:
          type: string
          minLength: 4
          maxLength: 280
          example: 'My content'
        user_id:
          type: integer
          format: int32
        url:
          type: string
          minLength: 4
          maxLength: 280
          example: 'My url'
        upvote:
          type: integer
          format: int32
        parent_id:
          type: integer
          format: int32
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
  
    Post:
      type: object
      properties:
        contribution:
          $ref: '#/components/schemas/Contribution'
        comment:
          $ref: '#/components/schemas/Contribution'
          
    ErrorResult:
      type: object
      properties:
        status:
          type: integer
          enum: [400, 401, 403, 404, 409]
        error: 
          type: string
          enum: ["Bad Request", "Unauthorized", "Forbidden", "Not Found", "Conflict"]
        message: 
          type: string
  
  examples:
    error400:
      value:
        status: 400
        error: "Bad Request"
        message: "Content is too long (maximum is 280 characters)"
    error401:
      value:
        status: 401
        error: "Unauthorized"
        message: "You provided no api key (X-API-KEY Header)"
    error403:
      value:
        status: 403
        error: "Forbidden"
        message: "Your api key (X-API-KEY Header) is not valid"
    error404:
      value:
        status: 404
        error: "Not Found"
        message: "No Tweet with that ID"